version: '3.4'

services:
  time-record-service-test:
    build:
      context: .
      dockerfile: .docker/Dockerfile.test
    environment:
      DB_URI: mongodb://trdb:27017
    depends_on:
      - trdb
    networks:
      - time-record

  trdb:
    image: mongo:4.4
    networks:
      - time-record

networks:
  time-record:
    driver: bridge
