apiVersion: v1
kind: Service
metadata:
  name: time-record-service
spec:
  type: ClusterIP
  selector:
    app: time-record
  ports:
  - name: grpc
    port: 50051
    targetPort: 50051
  - name: rest
    port: 8080
    targetPort: 8080
